name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          export KEYSTORE_PATH=${PWD}/release.keystore
          export KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          export KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          export KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          echo ${KEYSTORE_PATH}
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > ${KEYSTORE_PATH}
          ./gradlew app:assembleRelease --stacktrace

      - name: upload_arm64-v8a
        uses: actions/upload-artifact@v3
        with:
          name: app-arm64-v8a-release
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
      - name: upload_x86_64
        uses: actions/upload-artifact@v3
        with:
          name: app-x86_64-release
          path: app/build/outputs/apk/release/app-x86_64-release.apk
      - name: metadata.json
        uses: actions/upload-artifact@v3
        with:
          name: metadata.json
          path: app/build/outputs/apk/release/output-metadata.json
