name: Android CI

on:
  push:
    branches: ["main"]
    tags: [v*]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"
          submodules: "recursive"

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: "yuhaiin/code/go.mod"
          cache-dependency-path: "yuhaiin/code/go.sum"

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: front and rule
        run: |
          cd yuhaiin/code
          git clone --depth=1 https://github.com/yuhaiin/yuhaiin.github.io.git internal/http/out
          rm -rf internal/http/out/.git internal/http/out/.nojekyll
          go generate internal/http/generate.go
          curl https://raw.githubusercontent.com/yuhaiin/yuhaiin/ACL/yuhaiin/yuhaiin.conf -o internal/statics/bypass.conf
          go generate internal/statics/generate.go

      - name: build yuhaiin aar
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          sh yuhaiin/build.sh

      - name: Build with Gradle
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/release.keystore
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo ${KEYSTORE} | base64 -d > ${KEYSTORE_PATH}
          chmod +x gradlew
          ./gradlew app:assembleRelease --stacktrace

      - name: upload_arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release
          path: app/build/outputs/apk/release/yuhaiin-arm64-v8a-release.apk
      - name: upload_x86_64
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-release
          path: app/build/outputs/apk/release/yuhaiin-x86_64-release.apk
      - name: metadata.json
        uses: actions/upload-artifact@v4
        with:
          name: metadata.json
          path: app/build/outputs/apk/release/output-metadata.json
